### ISSUE TITLE
Not able to Access the Composer REST Server

### ISSUE THREAD

**Issue by vishwasrao** [IBM-Blockchain/ibm-container-service#11]
Hi,
I am following steps given in https://ibm-blockchain.github.io/interacting/
for step 4. Start and Access the Composer REST Server
It is expecting businessnetworkid , here i am giving business network name which i used while using composer playground.
I am able to create rest server successfully.

`vishwasrao@vishwasrao-desktop:~/Desktop/projects/blockchain/hyperledger/ibm-container-service/cs-offerings/free/scripts$ ./create/create_composer-rest-server.sh agentbroker
Preparing yaml file for create composer-rest-server
Creating composer-rest-server pod
Running: kubectl create -f /home/vishwasrao/Desktop/projects/blockchain/hyperledger/ibm-container-service/cs-offerings/free/scripts/../kube-configs/composer-rest-server.yaml
deployment "composer-rest-server" created
Creating composer-rest-server service
Running: kubectl create -f /home/vishwasrao/Desktop/projects/blockchain/hyperledger/ibm-container-service/cs-offerings/free/scripts/../kube-configs/composer-rest-server-services.yaml
service "composer-rest-server" created
Composer rest server created successfully
vishwasrao@vishwasrao-desktop:~/Desktop/projects/blockchain/hyperledger/ibm-container-service/cs-offerings/free/scripts$ 
`

But when trying to access it using 
`http://YOUR_PUBLIC_IP_HERE:31090/explorer/`
I am not able to load explorer
I am getting message 
This site can’t be reached

My Business Network Name is : agentbroker
If I want to give business network id , where can i find it?
I am not doing any changes & just following steps given.

Thanks,
Vishwas

**Comment by Pasteis** [comment]
I have same issue from a clean deployment into new cluster. It appears to be set up correctly but get the same error as Vishwas reported above. The Playground seems to work correctly.

**Comment by dhyey20** [comment]
https://github.com/IBM-Blockchain/ibm-blockchain.github.io/issues/40
It is the same issue as this one. We will try to post the updated instructions ASAP.

**Comment by vishwasrao** [comment]
Hi All,
 I got it resolved :)
let me share some thoughts here.
1. While creating REST server it asks for business network ID, to be frank i do not know from where I can get this id. But while going through github repo i come to know commit comment ans business network name. So I tried with business network name.
So may be we need to change docs or command while creating REST server.
2. I was doing mistake of creating business network for Web Browser and not on hlfv1.
When you open Composer first time, it will have two options for creating business network.
one with Web Browser and below that for hlfv1, Common mistake can be creating creating business network on web browser and then creating rest server for that,

Let me know if its clear or we need to do some changes in docs 
Thanks,
Vishwas

**Comment by Pasteis** [comment]
I suggest an update in docs to make it more clear that where this business network identity is defined when you use Composer. Assuming it's the Composer UI field "Give your new Business Network a name:" that is relevant? And second, while Composer details difference between Web Browser and hlfv1, this tutorial should just state "use hlfv1" to be as accurate as possible.

**Comment by dhyey20** [comment]
https://github.com/IBM-Blockchain/ibm-blockchain.github.io/pull/41/

Instructions have been updated. Feel free to re-open if the problem arises again.

**Comment by tzhang995** [comment]
This is happening to me. I did everything in the instructions and the output is the same "Composer rest server created successfully" but http://YOUR_PUBLIC_IP_HERE:31090/explorer/ does not work. Is there any idea as to how to fix this?

**Comment by letramos** [comment]
Hello, Im also facing same issue. Is there any way to re-open this topic? I run the install script with the instructions provided: create_composer-rest-server.sh --business-network-card INSERT_BIZNET_CARD_NAME
My business network name: basic-sample-network
User: admin
I run the script as: create_composer-rest-server.sh --business-network-card admin@basic-sample-network. 
I did not get any error during installation but if I try to access http://184.172.250.196:31090/explorer/ Im receiving: "The connection has timed out".

**Comment by inzi119** [comment]
still the same error, i followed every instruction and it doesn't work.
When I type "kubectl get svc"

```

 NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                           AGE
blockchain-ca                     NodePort    172.21.52.239    <none>        30054:30054/TCP                   7h
blockchain-orderer             NodePort    172.21.184.163   <none>        31010:31010/TCP                   7h
blockchain-org1peer1        NodePort    172.21.227.83    <none> 30110:30110/TCP,30111:30111/TCP   7h
> blockchain-org2peer1     NodePort    172.21.53.205    <none> 30210:30210/TCP,30211:30211/TCP   7h
> composer-playground    NodePort    172.21.94.248    <none>        8080:31080/TCP                    7h
> composer-rest-server     NodePort    172.21.18.249    <none>        3000:31090/TCP                    3h
> kubernetes                       ClusterIP   172.21.0.1           <none>        443/TCP                           7h

```

**Comment by jonglee** [comment]
Is there a solution for this?  I have a similar problem that can't reach the rest server

"This site can’t be reached"

**Comment by jonglee** [comment]
Never mind.  Figured it out.

1) make sure to use "hlfv1" not Web Browser option.
2) do this:  ./create/create_composer-rest-server.sh --business-network-card admin@animaltracking-network

where originally I did not have "admin@" in the argument.
