### ISSUE TITLE
What is the `pulse` container for?

### ISSUE THREAD

**Issue by iwinoto** [IBM-Blockchain/ibm-container-service#111]
In `kube-configs/blockchain.yaml` the pod spec for Deployment named `blockchain-orderer` has a container named `pulse`. The container executes the following script (lines added for readability):
```
UUID=$(cat /proc/sys/kernel/random/uuid) && while [ true ];
do
    curl https://ics-endpoint.mybluemix.net/pulse/beat/$UUID;
    sleep 10;
done
```
What is this for?

**Comment by mrshah-at-ibm** [comment]
The pulse container is sending a heart beat so someone it can be known how many instances are running.
