### ISSUE TITLE
composer-card-import fails during installation initiated by ./create_all.sh --with-couchdb script

### ISSUE THREAD

**Issue by bryq3** [IBM-Blockchain/ibm-container-service#115]
The blockchain deployment process get stuck at the step "Waiting for composer-card-import container to be Completed" when using the latest scripts. The very same message is returned once and again, endlessly. 

Anybody please help?
Thanks in advance.

**Comment by rthatcher** [comment]
I have just tried this and I see "Waiting for composer-card-import container to be Completed" about 30 times, then it completes OK.

Are you still seeing the problem?  It looks like issues #108 and #110 have had the same problem but I think it has been resolved with a new .yaml file.

I would suggest deleting the `ibm-container-service` folder and cloning the latest versions of the scripts and yamls `git clone https://github.com/IBM-Blockchain/ibm-container-service`

Then run the `deleteAll.sh` script and then finally the `./create_all.sh --with-couchdb`

**Comment by bryq3** [comment]
Hi, i followed your advice, but without positive result. The same situation - message "Waiting for composer-card-import container to be Completed" is printed constantly. I was waiting but there was no result.

**Comment by rthatcher** [comment]
Are you using "free" or "paid" option with the scripts?

Can you check your file: 

`ibm-container-service/cs-offerings/kube-configs/composer-card-import.yaml`

and see if it contains these lines:
```
    - name: K8S_PROFILE
      value: >
        {
          "name": "hlfv1",
          "x-type": "hlfv1",
          "version": "1.0.0",
          "peers": {
            "peer0.org1.example.com": {
                "url": "grpc://blockchain-org1peer1:30110",
                "eventUrl": "grpc://blockchain-org1peer1:30111"
              }
            },
          "certificateAuthorities": {
            "ca.org1.example.com": {
              "url": "http://blockchain-ca:30054",
              "caName": "CA1"
            }
          },
          "orderers": {
            "orderer.example.com": {
              "url": "grpc://blockchain-orderer:31010"
            }
          },
       ...
```

**Comment by bryq3** [comment]
I'm using free option of scripts (at least i think so). I checked and i have those lines mentioned above, in composer-card-import.yaml

**Comment by rthatcher** [comment]
This is odd, that you have the same Scripts, and are using the same procedure steps as me.  I assume that you are working with IBM Cloud, not some other Kubernetes Container service?

I'm running my Blockchain Cluster on the UK Data centre - where are you running yours? - perhaps you could use a different Data Centre as a test?  (This is the command that determines the data centre used `bx api api.ng.bluemix.net`.)

If that doesn't help, I think the next step would be to run the create scripts individually and check results, rather than running "create_all.sh".

**Comment by bryq3** [comment]
I deleted previous cluster (location US - south), created new (location UK) and did everything from the scratch. I don't know now if it was because the cluster data centre, but now it's working! Thank you @rthatcher for your help, i wouldn't manage to fix it without you!
