### ISSUE TITLE
Error trying to ping. No business network has been specified for this connection

### ISSUE THREAD

**Issue by gitjps** [IBM-Blockchain/ibm-container-service#118]
Followed [your instructions](https://github.com/IBM-Blockchain/ibm-container-service/issues/117), I now can access the Rest service.

Occasionally I get an error when opening the Playground:

**Error trying to ping. No business network has been specified for this connection**

I can then click on PeerAdmin | My Business Networks and reach the Playground regardless
These are the 2 cards I can see:

- PeerAdmin@hlfv1, USER ID: PeerAdmin, BUSINESS NETWORK: **none**
- admin@perishable-network, USER ID: admin. BUSINESS NETWORK: perishable-network

```
$ composer card list
The following Business Network Cards are available:

Connection Profile: hlfv1
┌─────────────────┬───────────┬──────────────────┐
│ Card Name       │ UserId    │ Business Network │
├─────────────────┼───────────┼──────────────────┤
│ PeerAdmin@hlfv1 │ PeerAdmin │                  │
└─────────────────┴───────────┴──────────────────┘


Issue composer card list --card <Card Name> to get details a specific card

Command succeeded
```

Not sure if that's ok

**Comment by davidkel** [comment]
Not sure why you get that error occasionally. The cards you see in playground are the ones I would expect to see. Not sure where you performed the composer card list but that isn't showing the contents of the card store used by playground or the rest server. Their card store is in shared storage and are set up to use the same card store, so what you see in playground will be the contents of that card store.

**Comment by gitjps** [comment]
My fault. I missed something in the installation, thx
