### ISSUE TITLE
Error deploying/starting business network on Composer Playground

### ISSUE THREAD

**Issue by odrodrig** [IBM-Blockchain/ibm-container-service#119]
I followed [this guide](https://ibm-blockchain.github.io/) to deploy a HLFV1.1 network with composer on IBM Kubernetes Service but am getting the following error when trying to deploy a network: 

> Error trying to start business network. Error: No valid responses from any peers. Response from attempted peer comms was an error: Error: 2 UNKNOWN: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code ENOTFOUND npm ERR! errno ENOTFOUND npm ERR! network request to https://registry.npmjs.org/composer-common failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443 npm ERR! network This is a problem related to network connectivity. npm ERR! network In most cases you are behind a proxy or have bad network settings. npm ERR! network npm ERR! network If you are behind a proxy, please make sure that the npm ERR! network 'proxy' config is set properly. See: 'npm help config' npm ERR! A complete log of this run can be found in: npm ERR! /root/.npm/_logs/2018-09-28T16_23_46_620Z-debug.log "

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/12896721/46221035-90713a00-c311-11e8-9f91-8087b12673c2.png">

**Steps to reproduce**: 
1. Follow guide at https://ibm-blockchain.github.io/ for creating the network on a free cluster
2. Go to your playground instance and try deploying a business network

**Comment by davidkel** [comment]
@odrodrig @timroster This is due to changes in the way IBM K8s handles creation of new containers now. Because of this change it no longer possible to run node.js chaincode in this environment. 
As a result support for Composer has been removed and the scripts updated to reflect this.
