### ISSUE TITLE
Upgrade Fabric-ca 1.0.2 to 1.4.0 via docker image, restart fabric-ca-server, when register, and then error! 

### ISSUE THREAD

**Issue by shiyunlai** [IBM-Blockchain/ibm-container-service#123]
Upgrade Fabric-ca from 1.0.2 to 1.4.0, restart fabric-ca docker container with old config and cert & private key, then exec fabric-ca-client register like this: 

$ fabric-ca-clien register --id.name test --id.type user --id.affiliation  org1.department1 --id.attrs 'hf.Revoker=true,foo=bar' 

and error message is (in docker container logs file): 

99.xx.xx.xx:port  POST /api/v1/identities 401 26 “Untrusted certificate: Failed to verify certificate: x509: certificate signed by unknown authority”

what's the matter? and how can i do !?

3Q!

**Comment by mrshah-at-work** [comment]
We do not support this repository any more as it has been moved to Archives. Thank you for your interest. Please check out IBM Blockchain V2 at https://cloud.ibm.com/catalog/services/blockchain

**Comment by shiyunlai** [comment]
@mrshah-at-ibm 3Q!

The above problem has been solved.
Before, the ca-chain.pem lacks the certificate information of the root ca. Use the correct ca-chain.pem.
