### ISSUE TITLE
Need channel/chaincode logs

### ISSUE THREAD

**Issue by debrajo** [IBM-Blockchain/ibm-container-service#13]
We're installing chaincode to this fabric setup using the fabric sdk.  How do we get to the channel/chaincode logs?

**Comment by dhyey20** [comment]
Based on PR: https://github.com/IBM-Blockchain/ibm-container-service/pull/9, the chaincode logs go to the peers log. Channel logs were already a part of the peer logs (as well as the orderer logs).

Try using the kubernetes UI, using `kubectl proxy` and then opening the url `127.0.0.1:8001/ui` to see the logs. Or from the CLI use `kubectl logs <pod-name> [<container-name>]`

**Comment by debrajo** [comment]
Thank you!  I rebuilt the containers with the latest source and chaincode logs are now integrated in wiht peer logs ..
