### ISSUE TITLE
Add Instructions for customising the config

### ISSUE THREAD

**Issue by pastadin** [IBM-Blockchain/ibm-container-service#17]
It would be useful if there was information to help users to customise the scripts, for example using our own `configtx.yaml` and `crypto.yaml` files - how would we pass these into the pods?

Other general information about customising the scripts would be good (as well as some links to specific pages in the kubernetes docs to serve as a pre-requisite to getting stated modifying them).

**Comment by dhyey20** [comment]
The only way that the user will be able to change the configs is by making a new image. So for eg. if someone wants to change `configtx.yaml` they can do something like:

Dockerfile:
```
FROM ibmblockchain/fabric-tools:1.0.1
COPY configtx-custom.yaml /sampleconfig/configtx.yaml
```

and then build the image
`docker build -f Dockerfile -t custom-tag .`

push the image to personal dockerhub
`docker login`
`docker push custom-tag`
`docker logout`

change the tools image in the `kubeconfig/*.yaml` from `ibmblockchain/fabric-tools:1.0.1` to `custom-tag`.

**Comment by mrshah-at-ibm** [comment]
@pastadin did the above mentioned solution work for you? Can we close this?
