### ISSUE TITLE
cs-offerings/free/scripts/create/create_storage.sh should be checking for shared-pvc not shared-pv

### ISSUE THREAD

**Issue by ptuton** [IBM-Blockchain/ibm-container-service#20]
Lines 11 and 19 in cs-offerings/free/scripts/create/create_storage.sh are currently:
`if [ "$(kubectl get pvc | grep shared-pvc | awk '{print $3}')" != "shared-pv" ]; then`

These lines appear to be checking for a **persistent volume claim** with the name `"shared-pv"`. This is the name of the *persistent volume*, not the *persistent volume claim*. I believe these lines should be checking for a with a name of `"shared-pvc"`. 

As such, these lines should be:
`if [ "$(kubectl get pvc | grep shared-pvc | awk '{print $1}')" != "shared-pvc" ]; then`

Note there are *two* changes: the name to check and the column to check ($3 contains the persistent volume name whereas we're looking for a persistent volume *claim* name, which is returned in $1).

**Comment by mrshah-at-ibm** [comment]
@ptuton thanks for reporting this. We will be fixing it in our next PR today.

**Comment by dhyey20** [comment]
@ptuton 
```$(kubectl get pvc | grep shared-pvc | awk '{print $3}')" != "shared-pv"```
Here we wanted to check that the `shared-pvc` volume claim is bound to `shared-pv` persistant volume. What you are telling will also work, but the thing we want to check is the relation between `shared-pv` and `shared-pvc`.

**Comment by mrshah-at-ibm** [comment]
https://github.com/IBM-Blockchain/ibm-container-service/pull/26 fixes this.
