### ISSUE TITLE
Advanced Install Steps Need Updated Commands

### ISSUE THREAD

**Issue by altharp** [IBM-Blockchain/ibm-container-service#27]
I attempted to follow the “Advanced Install” [instructions](https://ibm-blockchain.github.io/advanced/)) and the first command to join a channel did not finish.  The symptom was that a “Waiting for joinchannel container to be Completed” message was output repeatedly and the operation did not finish.  This was observed using code cloned from [https://github.com/IBM-Blockchain/ibm-container-service](https://github.com/IBM-Blockchain/ibm-container-service) on October 12.

I determined that the issue was that the command in the documentation did not have the same content as the cs-offerings/scripts/create_all.sh script (which did run to completion successfully).

Below is a list of steps that I think need to be updated.
1.  Step 2.4 for joining Org1 to channel1 – substitute command from create_all.sh
2.  Step 2.5 for joining Org2 to channel1 – substitute command from create_all.sh
3.   Step 3.2 for creating and starting the Composer REST server – The create_all.sh file has this step commented out and indicates that the user has to perform manual actions in the Composer Playground first.  I think this should be clarified in the documentation.  Step eleven on [this page](https://ibm-blockchain.github.io/reference/) says that a business network definition needs to be deployed before creating and starting the Composer REST server.  It would be helpful to mention this in the “Advanced Install” instructions (or remove the step or re-order it).
4.  Step 4.1 for installing chaincode on the Org1 peer – substitute command from create_all.sh
5.  Step 4.2 for installing chaincode on the Org2 peer – substitute command from create_all.sh
6.  Step 4.3 for instantiating chaincode on channel1 – substitute command from create_all.sh

**Comment by dhyey20** [comment]
Thanks @altharp for reporting this. Most of the issues are because of the changed ports, that were not reflected in the documentation. Making those changes and trying to make sure that we dont miss changing ports at other places.

**Comment by dhyey20** [comment]
https://github.com/IBM-Blockchain/ibm-blockchain.github.io/pull/53, made this PR to fix the issues.
