### ISSUE TITLE
Updating composer yamls for helm charts

### ISSUE THREAD

**Issue by dhyey20** [IBM-Blockchain/ibm-container-service#29]
@jt-nti Raised this issue.
```
There also seem to be three files in the helm-charts/ibm-blockchain-composer/templates/ directory. No idea what those are for though, and they are already missing the ID card updates.
```

We need to update the helm charts to be in-sync with the kubernetes yamls.

**Comment by jt-nti** [comment]
Out of interest, what are the helm charts?

**Comment by dhyey20** [comment]
Same way as nodejs has npm modules, kubernetes supports package management using helm charts. So if you do `helm install blockchain` pointing to your kubernetes cluster, then it will start a blockchain network (given once they accept our charts/ PR is pending). You can see more about it here: https://github.com/kubernetes/helm/blob/master/docs/charts.md
