### ISSUE TITLE
cannot open Rest API UI

### ISSUE THREAD

**Issue by itsdeepakrai** [IBM-Blockchain/ibm-container-service#34]
We have deployed this in BLuemix Kubernetes , UI is here http://173.193.120.98:31080/login
But we are unable to open the REST API UI , which ideally according to the documentation https://ibm-blockchain.github.io/interacting/ should be available   http://173.193.120.98:31090/explorer/

**Comment by mrshah-at-ibm** [comment]
@itsdeepakrai Did you follow the steps (3) and (4) on https://ibm-blockchain.github.io/interacting/ ? You need to deploy a business network on composer playground to be able to use the rest server.

**Comment by ykcai** [comment]
Had similar problems running the ./create_composer-rest-server.sh script but no REST API was showing up. `kubectl proxy` tells me that my composer-rest-server is running but i did not see it on `:31090/explorer/` and i had a network deployed. A new and clean cluster resolved this.

**Comment by CarlitoIBM** [comment]
Hello, I am facing the same issue. I deployed the business network but it seems that the rest server cannot recognize it:
`Error trying to query business network. Error: could not find chaincode with name 'my-network' - make sure the chaincode my-network has been successfully instantiated and try again`

**Comment by dhyey20** [comment]
@itsdeepakrai any updates? Did it work for you?
