### ISSUE TITLE
As an Administrator I want to be able to deploy blockchain into IBM Cloud Private

### ISSUE THREAD

**Issue by dwakeman** [IBM-Blockchain/ibm-container-service#35]
I have tried to use these scripts to deploy to IBM Cloud Private, but something seems to go wrong with the bootstrap process for the orderer.  My instance if ICp does have NFS as a storage type, and it has multiple workers, but I noticed the persistent volumes use Hostpath.  Is that an issue?

Thanks!

**Comment by mrshah-at-ibm** [comment]
yes, that is an issue. we can add a template for it.

**Comment by mrshah-at-ibm** [comment]
There are PVCs now under _paid_ to use IBM Container Service's paid NFS storage. It can be edited to use any NFS storage.

Closing this.
