### ISSUE TITLE
Unformatted instructions at the end of "Advanced Instructions" page

### ISSUE THREAD

**Issue by eacoeytaux** [IBM-Blockchain/ibm-container-service#38]
At the very bottom of the "Advanced Instructions" page there is the unformatted text `echo “” echo “=> CREATE_ALL: Running instantiate chaincode on channel "channel1" using "Org1MSP"” CHANNEL_NAME=”channel1” CHAINCODE_NAME=”example02” CHAINCODE_VERSION=”v1” MSP_CONFIGPATH=”/shared/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp” PEER_MSPID=”Org1MSP” PEER_ADDRESS=”blockchain-org1peer1:30110” create/chaincode_instantiate.sh` without any context.

**Comment by mrshah-at-ibm** [comment]
This was fixed by the above mentioned PR
