### ISSUE TITLE
Add to the disclaimer info on the network pulse (issue #41) 

### ISSUE THREAD

**Issue by ibmmark** [IBM-Blockchain/ibm-container-service#43]
Issue #41 Adds a small container in the orderer pod which sends a GET request to a pulse endpoint every 10 seconds. This to allow maintainers to keep track of how many blockchain networks are currently active on ibm container service.

The only data sent is a UUID which serves to identify repeated pulses from the same network. This UUID is not attached to any client data and is not persisted anywhere other than in the pulse endpoint. The UUID is re-generated whenever the pulse container goes down and comes back up.

**Comment by ibmmark** [comment]
I propose to add the following to the disclaimer documentation:

"For serviceability needs regarding the number of network activity, IBM has added a mechanism in the ordering service to collect a "pulse" from the networks. The UUIDs are collected periodically, there is no blockchain or transaction information or data gathered or accessed, it's only purpose is provide information on activity passing through the ordering service."

How does ^^ sound?

@mrshah-at-ibm @mastersingh24

**Comment by mrshah-at-ibm** [comment]
@ajpauwels ^

**Comment by mastersingh24** [comment]
@ibmmark  - wording sounds good.  Check out the "Privacy Notice" [here](https://github.com/IBM-Blockchain-Archive/cp-web) that we had to put in for tracking deployments of the cp-web app.
So we might need to add a Privacy Notice section and put the wording under that

**Comment by ajpauwels** [comment]
I've added a Privacy Notice section and put in the slightly modified disclaimer from Mark, let me know what you guys think.
