### ISSUE TITLE
Error from server (NotFound): pods "utils" not found (Blockchain network install fails)

### ISSUE THREAD

**Issue by georg90** [IBM-Blockchain/ibm-container-service#44]
When trying to install the blockchain network I run into the following error (on macOS):

Using [this](https://ibm-blockchain.github.io/advanced/) tutorial in step 2:

``` 
./create/create_blockchain.sh
Creating Services for blockchain network
Running: kubectl create -f /ibm-container-service/cs-offerings/scripts/create/../../kube-configs/blockchain-services-free.yaml
error: Unexpected args: [- ibm-container-service/cs-offerings/scripts/create/../../kube-configs/blockchain-services-free.yaml]
See 'kubectl create -h' for help and examples.
Creating new Deployment
Running: kubectl create -f /ibm-container-service/cs-offerings/scripts/create/../../kube-configs/blockchain.yaml
error: Unexpected args: [- ibm-container-service/cs-offerings/scripts/create/../../kube-configs/blockchain.yaml]
See 'kubectl create -h' for help and examples.
Checking if all deployments are ready
No resources found.
Error from server (NotFound): pods "utils" not found
```

I ran the `export` command before following this step. But I think the config is not used?

**Comment by mrshah-at-ibm** [comment]
@georg90 can you provide us with following details?

1. Operating System where the kubectl client is running. I suspect this is a windows system and is not interpreting the `kubectl create -f` command correctly.
2. The output of `kubectl version`

**Comment by georg90** [comment]
As i wrote above, I am using macOS.

This is the output:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-09T07:27:47Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.4-1+1540c973d4ff9d", GitCommit:"1540c973d4ff9da2d6a204a7709084488a459ed4", GitTreeState:"clean", BuildDate:"2017-10-06T15:08:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mrshah-at-ibm** [comment]
@georg90 can you look into `./create/create_blockchain.sh` and run the commands manually?

Let's try the first command `kubectl create -f /ibm-container-service/cs-offerings/scripts/create/../../kube-configs/blockchain-services-free.yaml`.. Does it work or errors out?

**Comment by georg90** [comment]
This works:

```
kubectl create -f ../../kube-configs/blockchain-services-free.yaml
service "blockchain-ca" created
service "blockchain-orderer" created
service "blockchain-org1peer1" created
service "blockchain-org2peer1" created
```

**Comment by mrshah-at-ibm** [comment]
It will not work because of the errors in creating services and other components..

Can you try to run `. create_blockchain.sh` or `source create_blockchain.sh` or `sh create_blockchain.sh`?

**Comment by georg90** [comment]
same result. I think it has to do with the path settings, they might be off for macOS vs. linux structure? Since the script fails but the actual command works

**Comment by mrshah-at-ibm** [comment]
Looks like it is not interpreting https://github.com/IBM-Blockchain/ibm-container-service/blob/master/cs-offerings/scripts/create/create_blockchain.sh#L42 line correctly.

Can you add `echo ${KUBECONFIG_FOLDER}` right above that line? for some reason it is replacing `-f /ibm-container-service` in the command with `- ibm-container-service`

**Comment by georg90** [comment]
Output is as expected:
`ibm-container-service/cs-offerings/scripts/create/../../kube-configs`

**Comment by mrshah-at-ibm** [comment]
@georg90 I don't think the output is as expected.

It is missing the `/` before `ibm-container-service`

**Comment by georg90** [comment]
Sorry, that's an error on my side, the complete path hast a `/` in front of the path

**Comment by georg90** [comment]
Found the problem! My path included a `- ` - so the complete path was `/somwhere/some - thing/ibm..` This leads to the error.

Thank you @mrshah-at-ibm for your help! This can be closed
