### ISSUE TITLE
Cannot ping network after installing and starting it with fabric running on IBM Cloud Private

### ISSUE THREAD

**Issue by dwakeman** [IBM-Blockchain/ibm-container-service#45]
I used the `create_all.sh` script to deploy Fabric and Composer Playground to kubernetes on IBM Cloud Private.  I have an instance running in a VM on my mac, created using the script found [here](https://github.com/IBM/deploy-ibm-cloud-private).  That script gives me a working CP environment with 3 worker nodes and one master node, all running in separate virtual containers inside the VM.  It also includes an NFS service and several volumes predefined for me, so I tweaked the `storage-free.yaml` file to remove the PV definition.  When it runs the PVCs get bound to my existing volumes.  I am using composer 0.15.1.

I then used the Developer playground tutorial to deploy a business network I have deployed many times before.  To create the PeerAdmin card I ran this command to copy out the `/shared/crypto-config` directory from one of the pods:

`kubectl cp blockchain-org1peer1-815969561-th99r:/shared/crypto-config ./crypto-config`

Then I executed the commands found in the `createPeerAdminCard.sh` script to set the DIR, CERT and PRIVATE_KEY environment variables appropriately using the files from the crypto-config directory I copied out.  With that done I ran:

```
composer card create -p connection.json -u PeerAdmin -c "${CERT}" -k "${PRIVATE_KEY}" -r PeerAdmin -r ChannelAdmin

Successfully created business network card file to 
	Output file: PeerAdmin@icp-network.card

Command succeeded
```
```
composer card import -f PeerAdmin@icp-network.card

Successfully imported business network card
	Card file: PeerAdmin@icp-network.card
	Card name: PeerAdmin@icp-network

Command succeeded
```

Then I ran this command to install the runtime:
`composer runtime install -c PeerAdmin@icp-network -n prescription-network`

After that I ran this command to start my network:
```
composer network start -c PeerAdmin@icp-network -a prescription-network.bna -A admin -S adminpw
Starting business network from archive: prescription-network.bna
Business network definition:
	Identifier: prescription-network@0.6.11
	Description: Demo network for tracking medications and prescriptions
✔ Starting business network definition. This may take a minute...
Successfully created business network card to admin@prescription-network.card

Command succeeded
```
That step generates the network admin card (as I understand it) so I imported it.
```
composer card import -f admin@prescription-network.card

Successfully imported business network card
	Card file: admin@prescription-network.card
	Card name: admin@prescription-network

Command succeeded
```
When I try to do a network ping, it fails:
```
composer network ping -c admin@prescription-network
Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Error: Invalid results returned ::FORBIDDEN
Command failed
```
I don't have the output saved at this time, but when I ran it again I got text I have seen before, about not being able to serialize the identity, that it didn't know who issued the certificate.

I should say that before I did all this I deleted the `~/.composer` directory and the folder where I stored the crypto-config directory so that I didn't have any lingering old certs or keys.  I'm not sure if those are the only places.  I noticed that the connection.json still has a reference to a keyStore directory; I made sure to create new one, and verified that it was empty.

Am I doing something wrong?  Thanks!

**Comment by mrshah-at-ibm** [comment]
@sstone1 can you help?

**Comment by DennisM330** [comment]
I was able to deploying, start, and ping my business network using the latest version of the helm charts to deploy the underlying hyperledger fabric if did the composer runtime install, network start, composer card import, and composer network ping command from my Mac OS. If I tried to use a composer CLI pod to try and perform the composer network ping, the ping would timeout. All the other composer commands completed successfully in the composer CLI pod.
2017-12-07T15:06:52.773Z INFO    ConnectionProfileManager:getConnectionManagerByTy Looking up a connection manager for type {"0":"hlfv1"}$
2017-12-07T15:06:53.133Z INFO    ConnectionProfileManager:getConnectionManagerByTy Using this connection manager  {"0":{"connectionProfileManager":{}}}$
2017-12-07T15:09:00.909Z ERROR   HLFConnection           :enroll()                 {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.0.187:30054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.0.187:30054]\n    at caClient.enroll.then.then.then.then.catch (/home/composer/.npm-global/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$

**Comment by donbr** [comment]
Have you tried running the following script after downloading the card?

    cs-offerings/scripts/connection-profile/update_card.sh

**Comment by huyen-pk** [comment]
I got the same error when trying to ping network after properly install .bna

**Comment by DennisM330** [comment]
Can you elaborate on update_card.sh. What address do I used within ICP?

**Comment by DennisM330** [comment]
I got it to work. Make sure you use the external I/P address of ICP as follows in the composer-card-import.yaml
 
Also, ahead of time I edited the values.yaml in the ibm-blockchain-composer directory to specify the name of my business network card I knew I was going to deploy in the playground. Need to note this in the ReadMe file
 
 
 
name: K8S_PROFILE
      value: >
        {
          "type": "hlfv1",
          "name": "hlfv1",
          "orderers": [
              {
                  "url": "grpc://192.168.27.100:31010"
              }
          ],
          "ca": {
              "url": "http://192.168.27.100:30054",
              "name": "CA1"
          },
          "peers": [
              {
                  "requestURL": "grpc://192.168.27.100:30110",
                  "eventURL": "grpc://192.168.27.100:30111"
              }
          ],
          "channel": "channel1",
          "mspID": "Org1MSP",
          "timeout": 300
        }
 
 
blockchain:
  pullPolicy: Always
  composerRestServerCard: admin@digitalpartsnetworkv2
 
I then deploy my business network archive in the playground:
 
network: digitalpartsnetworkv2
card: admin@digitalpartsnetworkv2
identity:
         admin-user-id
         admin-password
 
Then I tested the connection to my business network and it suceeded
 
I then went to deployments and scaled the rest server to 0 and then back to 1 to force it to shutdown and restart.
 
The explorer now works:
http://192.168.27.100:31090/explorer/

**Comment by mrshah-at-ibm** [comment]
Thanks @DennisM330
