### ISSUE TITLE
Getting error when trying to import card in composer 

### ISSUE THREAD

**Issue by JayasreeVenugopal** [IBM-Blockchain/ibm-container-service#48]
Getting error as below, when trying to import an updated card/newly created card.
Error: Failed to save card: admin@test-bna
Command failed

Any help??

**Comment by davidkel** [comment]
@JayasreeVenugopal most likely cause is you don't have the right permissions to access the `.composer` directory in your home directory. This can be caused if you start mixing command invocation using sudo and then not using sudo. Our recommendation is to never use sudo when installing and using composer.

**Comment by lesleyannjordan** [comment]
@JayasreeVenugopal please reopen if this is still an issue after help given.
