### ISSUE TITLE
Start producing releases to keep track of working combination of components

### ISSUE THREAD

**Issue by mrshah-at-ibm** [IBM-Blockchain/ibm-container-service#49]
I want Sign-Off by @sstone1 @ajpauwels @dhyey-ibm before we cut the first release.

**Comment by dhyey20** [comment]
Lets wait till I fix #39 and we merge #41.

**Comment by mrshah-at-ibm** [comment]
We just produced a release for 1.0 fabric. We will do the same for 1.1
