### ISSUE TITLE
enroll against the ca not workin

### ISSUE THREAD

**Issue by knagware9** [IBM-Blockchain/ibm-container-service#5]
![image](https://user-images.githubusercontent.com/25450953/30022034-2393018c-9187-11e7-8861-a965b93a1bc6.png)
Its showing 

Sorry, we could not enroll the admin against the CA.

Edit the settings below to try again.

CA's api_url

enrollId

enrollSecret

**Comment by mrshah-at-ibm** [comment]
@knagware9 you will have to use the CA's URL from the connection profile mentioned at the end of https://ibm-blockchain.github.io/interacting/

It constitutes of your worker node's PUBLIC_IP and the port exposed by the service. You can find the public IP by executing  `bx cs workers blockchain`

**Comment by dhyey20** [comment]
@knagware9 any updates on this?

**Comment by mastreips** [comment]
https://github.com/IBM-Blockchain/marbles/issues/221 - don't run enrollAdmin.js and registerUser.js before running install and instantiate on chaincode. Run the gulp marbles-local command and it should work. You may have to teardown the network and make sure the certs/keys are removed from the hcf-key-store
