### ISSUE TITLE
update_card.sh - bug with card file name

### ISSUE THREAD

**Issue by rthatcher** [IBM-Blockchain/ibm-container-service#51]
If the user specifies a 'local' filename for the card e.g. `-c mycard.card` then the patched .card file gets created in the $TMPDIR and gets deleted!

The workaround is to specify the full path of the card e.g. `-c /home/rob/mycard.card`

Also the usage says `-f mycard.card` but the example uses `-c`

**Comment by davidkel** [comment]
@sstone1 https://github.com/IBM-Blockchain/ibm-container-service/pull/52
