### ISSUE TITLE
Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{"code":400,"message":"Authorization failure"}]] Command failed

### ISSUE THREAD

**Issue by booboothefool** [IBM-Blockchain/ibm-container-service#65]
Followed these instructions exactly as described:

1 https://ibm-blockchain.github.io/setup/
2 https://ibm-blockchain.github.io/simple/ (Option 1)

3 https://ibm-blockchain.github.io/interacting/

For Step "3. Develop And Deploy Your Business Network, I made a new business network under Connection: hlfv1 instead of Connection: hlfv1: Web Browser called `admin@biznet`.

```
Connection: hlfv1
[PeerAdmin@hlfv1][admin@biznet]
```

When clicking "Connect now ->" under `admin@biznet`, I get the error:
Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{"code":400,"message":"Authorization failure"}]]
Command failed

That steps that follow "4. Expose Your Business Network As A REST API" and "5. Ping the deployed business network from the CLI" fail as well.

**Comment by umeshsinghkushwaha** [comment]
@booboothefool What was the issue here? Are you able to resolve the same?

**Comment by erikvaningen** [comment]
I also would be very interested in this problem, got exactly the same.
