### ISSUE TITLE
Card Import Host Names are not resolvable in HELM Charts for ICP

### ISSUE THREAD

**Issue by DennisM330** [IBM-Blockchain/ibm-container-service#72]
The following host names cause time-out issues when trying to use in the business network card import. The newest version of the HELM charts from a few days ago are now using "ibm-blockchain-network-orderer, ibm-blockchain-network-ca, ibm-blockchain-network-orgpeer1". These values cause time-out issues and I have to use the external I/P address of IBM Cloud Private to get this to work. Need resolveable and reachable host names in this file for ICP.
"name": "hlfv1",
          "orderers": [
              {
                  "url": "grpc://ibm-blockchain-network-orderer:31010"
              }
          ],
          "ca": {
              "url": "http://ibm-blockchain-network-ca:30054",
              "name": "CA1"
          },
          "peers": [
              {
                  "requestURL": "grpc://ibm-blockchain-network-org1peer1:30110",
                  "eventURL": "grpc://ibm-blockchain-network-org1peer1:30111"
              }

**Comment by sstone1** [comment]
All the Composer scripts have been removed; closing.
