### ISSUE TITLE
Error connecting to Business Network after suspend and resume

### ISSUE THREAD

**Issue by DennisM330** [IBM-Blockchain/ibm-container-service#75]
Deployed hyperledger fabric and hyperledger composer to IBM Cloud Private using HELM charts. Brought up hyperledger composer and deployed and business network and was able to connect to the business network in the playground. Composer REST server was able to successfully connect using the business network card. Then did a vagrant suspend and resume of the environment. Composer REST server still works fine and is able to connect to the business network. Tried to connect to business network using the playground and get the following error:
Error: Error trying login and get user Context. Error: EINVAL: invalid argument, open '/home/composer/.composer/client-data/admin@digitalpartsnetworkv2/83a7803939f70121a0d0e8256f0383a1c8e6d35d5b5ae814666c1b0a9ad718d2-pub'

**Comment by mrshah-at-ibm** [comment]
#76 removes the chaincode and composer stuff from the helm-charts. The helm-charts should be used to setup the network and rest should be done by the scripts or manually.
