### ISSUE TITLE
delete_composer-rest-server script tries to find yaml in wrong location

### ISSUE THREAD

**Issue by joel-huang** [IBM-Blockchain/ibm-container-service#81]
Line 35 of delete_composer-rest-server.sh reads:
`kubectl delete -f ../kube-configs/composer-rest-server.yaml`
this points to scripts instead of cs-offerings where kube-configs is located

**Comment by EmanHerawy** [comment]
I fixed this bug by replacing .`./kube-configs/` with `${KUBECONFIG_FOLDER}`

**Comment by lesleyannjordan** [comment]
Looks like lines 34 and 35 require updating to use ${KUBECONFIG_FOLDER} rather than the direct directory referencing.

**Comment by mrshah-at-ibm** [comment]
Fixed by https://github.com/IBM-Blockchain/ibm-container-service/pull/87
