### ISSUE TITLE
Support multiple workers deployment

### ISSUE THREAD

**Issue by LordGoodman** [IBM-Blockchain/ibm-container-service#85]
We are using the HostPath type of  Persistent Volume, which is not support multiple worker nodes deployment, any plan to replace the PV type?

**Comment by mrshah-at-ibm** [comment]
We do support the non-hostpath types. Ref: https://github.com/IBM-Blockchain/ibm-container-service/blob/master/cs-offerings/kube-configs/storage-paid.yaml

**Comment by LordGoodman** [comment]
Is this solution only against the IBM cloud?

**Comment by mrshah-at-ibm** [comment]
This solution is for the IBM Cloud. Feel free to edit it to suit your needs.
