### ISSUE TITLE
should have required property 'x-type'

### ISSUE THREAD

**Issue by erikvaningen** [IBM-Blockchain/ibm-container-service#88]
`./update_card.sh`
works fine and generates an updated card and the original. 

The command
`composer card import -f admin.card`
goes wrong with this message:
**_Failed to import the business network card
message: should have required property 'x-type'_**

I am using:
- composer --version v0.19.2
- nvm --version 0.33.2
- nodejs --version v8.11.1

What could be the cause of this problem?

**Comment by KeanuTomatoMomotaro** [comment]
Correct me if I'm wrong, but I think the scripts [provided here](https://ibm-blockchain.github.io/) would install a version 0.16.2 composer playground with fabric 1.0.3. [A 0.16 card cannot be imported to a version 0.19 cli](https://github.com/hyperledger/composer/releases). If that is the case, try uninstalling the composer cli and reinstall the 0.16 version  `npm install -g composer-cli@0.16.6`. And finally, try again.

**Comment by lesleyannjordan** [comment]
@erikvaningen please indicate the scripts or tutorial you are following and which version of fabric you are running on top of please.

**Comment by erikvaningen** [comment]
My Playground is v0.16.2. I tried to uninstall composer-cli, it did not work well. 

I believe the 
https://ibm-blockchain.github.io/setup/
should indicate to install also the composer-cli v0.16.6 because now it would install the latest version ( v0.19.2). 

For now I am giving up on this route and will follow 
https://github.com/IBM/hyperledger-fabric-on-linux-one

But thanks for this clarification, now at least my problem is clear!

**Comment by sstone1** [comment]
Looks resolved; if not, Composer support has been removed anyway.
