### ISSUE TITLE
Update cs-offerings scripts to allow composer version 0.19

### ISSUE THREAD

**Issue by KeanuTomatoMomotaro** [IBM-Blockchain/ibm-container-service#89]
Are there plans to upgrade the scripts and configuration within the `cs-offerings` folder to allow deployment of composer 0.19?

<img width="1437" alt="screen shot 2018-04-30 at 09 39 59" src="https://user-images.githubusercontent.com/23183047/39505454-8e04d0f4-4dfc-11e8-8545-520a45b79418.png">

I successfully deployed composer playground to 0.19.2 by changing some of the configurations for the docker images but I was unable to deploy any new business networks on the deployed cluster. I believe this has something to do with the fabric version and channel configurations as well.

<img width="804" alt="screen shot 2018-05-02 at 11 35 18" src="https://user-images.githubusercontent.com/23183047/39505522-08df80da-4dfd-11e8-9df8-67adf4ba32cc.png">

**Comment by sstone1** [comment]
Composer support has been removed from these scripts.
