### ISSUE TITLE
trying to enable authentication for the REST server

### ISSUE THREAD

**Issue by ezmoneySniper** [IBM-Blockchain/ibm-container-service#92]
How and where do i config the REST API server? I have tried running the following command  but it does seem to work. My goal is to have the Wallet option appear in my API page. 

export COMPOSER_PROVIDERS='{
  "github": {
    "provider": "github",
    "module": "passport-github",
    "clientID": "REPLACE_WITH_CLIENT_ID",
    "clientSecret": "REPLACE_WITH_CLIENT_SECRET",
    "authPath": "/auth/github",
    "callbackURL": "/auth/github/callback",
    "successRedirect": "/",
    "failureRedirect": "/"
  }
}'

**Comment by vmorris** [comment]
Probably you meant to open this against https://github.com/hyperledger/composer

**Comment by ezmoneySniper** [comment]
i have been following this document https://ibm-blockchain.github.io/setup/ and have everything working. I just like to know how to config the REST api server so that i can enable Oauth.

**Comment by vmorris** [comment]
try this https://hyperledger.github.io/composer/unstable/integrating/enabling-multiuser.html

**Comment by ezmoneySniper** [comment]
so right now i created the api server using 
` cd cs-offerings/scripts/
 ./create/create_composer-rest-server.sh --business-network-card INSERT_BIZCARD_NAME`
so composer-rest-server is not an command that i can execute at this point.

Are you suggesting that i should create a new RESET server

**Comment by bryq3** [comment]
@ezmoneySniper did you manage to enable multiuser mode for rest server on cluster? If yes how did you do this? Could you please give me some hints?
